- hosts: all
  user: root
  tasks:
    - name: yum docker
      yum: name=docker-ce-19.03* state=present
    - name: start docker
      service: name=docker state=started enabled=yes
    - name: yum kubeadm
      yum: name=kubeadm-1.20.7 state=present
    - name: yum kubelet
      yum: name=kubelet-1.20.7 state=present
    - name: yum kubectl
      yum: name=kubectl-1.20.7 state=present
    - name: xg config
      shell: sed -i 's/KUBELET_EXTRA_ARGS=/KUBELET_EXTRA_ARGS="--pod-infra-container-image=registry.cn-hangzhou.aliyuncs.com/google_containers/pause-amd64:3.2"/'
---
- hosts: master
  user: root
  tasks:
    - name: Init initalize file
      shell: kubeadm config print init-defaults > new.yaml
    
